#!/usr/bin/bash
# v20240405
#   - dropped pgrep to support long binary/process names
#   - specify multiple apps separated by comma, eg, boinclasso -s milkyway_nbody,ap27_cpu
# v20240327
#   - update mechanism from GitHub added
# v20240326
#	- allow script to loop, then no longer requires cron 
#	- added help
# v20240325
#   - initial version
#

LANG=C
FILENAME=$(dirname $(readlink -f $0))/$(basename -- "$0")


help() {
    echo "Usage:"
    echo "  -l nn       - Script loops every nn seconds, no need to run from cron"
    echo "  -s string   - String & process to search for with pgrep"
    echo "  -h          - this help"
    echo "  -e          - evaluate"
    echo "  -u          - update script from GitHub"
    exit 0
}

main() {
    processIDs=$(ps -ef | egrep "$(echo $1 | tr ',' '|')" | egrep -v " grep|boinclasso" | awk '{ print $2 }')
    l3Caches=$(lscpu -e | grep -v "CPU" | tr ':' ' ' | awk '{ print $8 }' | sort -u | wc -l)
    numWUs=$(echo ${processIDs} | wc -w)
    
    if [[ ${numWUs} -gt ${l3Caches} ]]; then
        echo "There are more WUs than L3 complexes, unsupported scenario!"
        exit 1
    elif [[ ${numWUs} -lt ${l3Caches} ]]; then
        echo "Less WUs than L3 complexes, likely wasting rescources!"
    fi  

    L3counter=0
    for PID in $(echo ${processIDs}); do
        cpuList=$(lscpu -e | egrep ":${L3counter} " | awk '{ print $1 }' | xargs | sed 's/ /,/g')
        echo taskset -a -p -c ${cpuList} ${PID}
        taskset -a -p -c ${cpuList} ${PID} > /dev/null
        L3counter=$((L3counter+1))
    done
}

eval() {
    CPU=$(awk -F": " '/model name/ { print $2 }' /proc/cpuinfo | sort -u)
    CPUs=$(lscpu | awk '/^CPU\(s\):/ { print $2 }')
    l3Caches=$(lscpu -e | grep -v "CPU" | tr ':' ' ' | awk '{ print $8 }' | sort -u | wc -l)
    l3Size=$(lscpu | awk '/L3 cache:/ { print $3 }')
    echo "CPU:          $CPU"
    echo "L3 Caches:    $l3Caches"
    echo "$CPUs"
    echo "$l3Size"
    echo "Ideal # threads $(($CPUs/$l3Caches))"
    echo "Ideal # WUs $(($CPUs/$l3Caches))"
    exit 0
}

update_script() {
	if [[ $(id -u) -ne 0 ]]; then
		echo "You need to be root to perform this operation. aborting..."
	else
		script_download="https://raw.githubusercontent.com/MBlenn/BOINC/master/BOINC%20lasso/boinclasso"
		wget -O ${FILENAME}_tmp ${script_download}
		VERSION_OLD=$(awk '/^# v20/ { print $2 }' ${FILENAME} | sed 's/v//' | head -1)
		VERSION_NEW=$(awk '/^# v20/ { print $2 }' ${FILENAME}_tmp | sed 's/v//' | head -1)
		echo "OLD: $VERSION_OLD"
		echo "NEW: $VERSION_NEW"

		if [[ $VERSION_NEW -gt $VERSION_OLD ]]; then
			chmod +x ${FILENAME}_tmp
			mv ${FILENAME}_tmp ${FILENAME}
		else
			echo "Local is same or newer version than on the repo!"
		fi
			
	fi
    exit
}

while getopts ehul:s: opt
do
   case $opt in
        l) loop=$OPTARG; echo "Executing every $loop seconds";;
        s) string=$OPTARG;;
        h) help;;
        e) eval;;
        u) update_script;;
        *) help;;
   esac
done

version=$(awk '/^# v20/ { print $2 }' ${FILENAME} | head -1)
echo "Local version: $version"

if [[ -z $string ]]; then
    echo "No process defined, can't continue"
    exit 1
fi

if [[ -z $loop ]]; then
    main $string
    exit 0
else
    while true; do 
        main $string
        sleep $loop
    done
fi